name: 'Kubernetes CLI'
description: 'Run kubectl commands'
author: 'equipotoctoc'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  args:
    description: 'Arguments to pass to kubectl'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DOCKER_BUILDKIT: "1"
    BUILDKIT_PROGRESS: "plain"
    BUILDX_PLATFORM: "linux/amd64,linux/arm64"
  args:
    - ${{ inputs.args }} 